namespace:
  name: demo

replica:
  count: 3

image:
  repository: nginx
  tag: alpine
  pull:
    policy: IfNotPresent

resource:
  cpu: 50m
  memory: 256Mi

service:
  type: ClusterIP
  port: 8111

configmap:
  data: "version: alpine"
